name: tomdoc.sh

on:
  push:
    branches-ignore:
      - master

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install tomdoc.sh
      run: |
        git clone git://github.com/tests-always-included/tomdoc.sh.git
        cd tomdoc.sh
        make install
    - name: Run tomdoc.sh
      run: |
        export PATH=$PATH:$HOME/bin
        chmod +x .github/scripts/gen-doc.sh
        .github/scripts/gen-doc.sh
    - name: Commit doc
      run: |
        git add -f docs
        if [[ -z "$(git status --porcelain | grep -o "^[^ ?]")" ]]; then
          echo "nothing to commit"
          exit 0
        fi
        git config --global user.email "none@none"
        git config --global user.name "GitHub Action"
        git commit -m "ci skip: update docs"
        git push
